### ISSUE TITLE
write.GGUM2004() typo

### ISSUE THREAD

**Issue by jsparks8** [jorgetendeiro/GGUM#8]
Hello,

Write.GGUM2004() exports a command file document with specified arguments for GGUM2004 to execute; however, the criterion argument is output as follows:
"0,001 CRITERION"

This leads to an error within the program and requires manually editing the document to:
"0.001 CRITERION"

After which the command file runs successfully.

Thank you for this great package, just wanted to bring this to your attention!

**Comment by secastroal** [comment]
Dear Jordan,

Thank you for letting us know about this typo. 
We have already fixed it in our latest commit. The package will be updated in CRAN in the following weeks.

Best, 
Sebastian
